pipeline {
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        stage('Checkout'){
           steps {
                url: 'https://github.com/rajeshmamuddu/jenkins-pipeline/python-jenkins-argocd-k8s',
           }
        }

        stage('Build Docker'){
            steps{
                script{
                    sh '''
                    echo 'Buid Docker Image'
                    docker build -t rajesh4851/cicd-e2e:${BUILD_NUMBER} .
                    '''
                }
            }
        }

        stage('Push the artifacts'){
           steps{
                script{
                    sh '''
                    echo 'Push to Repo'
                    docker push rajesh4851/cicd-e2e:${BUILD_NUMBER}
                    '''
                }
            }
        }
    }
}
