pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('build') {
      agent {
        docker { image 'pengbai/docker-supermario' }
      }
      steps {
        sh 'docker pull pengbai/docker-supermario'
      }
    }
  }
}
