pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('build') {
      agent {
        docker { image 'pengbai/docker-supermario' }
      }
      steps {
        sh 'echo penguin image'
      }
    }
    stage('deploy') {
      agent {
        docker { image 'pengbai/docker-supermario' }
      }
      steps {
        script {
                  // Your deployment steps here
                  sh 'docker run -p 8600:8080 -d rajesh4851/pengbai/docker-supermario:latest'
              }
    }

  }
}
